block_name
~~~~~~~~~~~

**type**: ``string`` **default**: le nom du formulaire (voir :ref:`Savoir quel block personnaliser <cookbook-form-customization-sidebar>`)

Vous permet de surcharger le nom du block utilisé pour afficher le type
de formulaire. Utile par exemple si vous avez plusieurs instances d'un
même formulaire et que vous avez vesoin de personnaliser l'affichage
de chaque formulaire individuellement.