auto_initialize
~~~~~~~~~~~~~~~

**type**: ``boolean``  **default**: ``false``

Une option interne : définit si le formulaire doit être initialisé
automatiquement ou non. Pour tous les champs, cette option devrait toujours
valoir ``true`` pour les formulaires de base. Et puisqu'un bouton ne peut pas
être un formulaire complet à lui seul, l'option est définie à ``false``.
Vous n'aurez pas besoin de changer cette option et vous n'aurez probablement
jamais à vous en soucier.