constraints
~~~~~~~~~~~

**type**: array ou :class:`Symfony\\Component\\Validator\\Constraint` **default**: ``null``

Vous permet de rajouter une ou plusieurs contraintes de validation à un champ
spécifique. Pour plus d'informations, consultez :ref:`Ajoutez une validation<form-option-constraints>`.
Cette option est ajoutée dans la classe :class:`Symfony\\Component\\Form\\Extension\\Validator\\Type\\FormTypeValidatorExtension`.
