widget
~~~~~~

**type**: ``string`` **default**: ``choice``

Désigne la manière sont le champ doit être affiché. Cette option accepte les
cas suivants :

* ``choice``: Affiche trois listes déroulantes. L'ordre des liste est défini
  par l'option `pattern`_.

* ``text``: Affiche trois champs textes (mois, jour, année).

* ``single_text``: Affiche un unique champ texte. La saisie de l'utilisateur sera
  validé en se basant sur l'option `format`_.
