inherit_data
~~~~~~~~~~~~

.. versionadded:: 2.3
    Cette option était connu sous le nom de  ``virtual`` avant Symfony 2.3.

**type**: ``boolean`` **default**: ``false``

Cette option indique si le formulaire hérite des données du formualaire parent.
Elle peut être utile si vous avez à définir un lot de champs qui sont dupliqués
dans plusieurs formulaires, consultez :doc:`/cookbook/form/inherit_data_option`.
