multiple
~~~~~~~~

**type**: ``Boolean`` **default**: ``false``

Si cette option est à true, l'utilisateur sera capable de sélectionner
plusieurs option (en opposition au choix d'une option et une seule).
Selon la valeur de l'option ``expanded``, cela affichera une liste déroulante
ou des checkboxes si elle est à true, ou une liste déroulante ou des boutons
radios si elle est à false.
La valeur retournée sera un tableau.