required
~~~~~~~~

**type**: ``Boolean`` **default**: ``true``

Si cette option est à true, un `attribut HTML5 required`_ sera affiché. 
La balise ``label`` correspondante s'affichera également avec une classe ``required``.

C'est une fonctionnalité indépendante de la validation et qui
This is superficial and independent from validation. At best, if you let Symfony
guess your field type, then the value of this option will be guessed from
your validation information.

.. _`HTML5 required attribute`: http://diveintohtml5.info/forms.html