Liste déroulante, checkboxes ou boutons radio
---------------------------------------------

Ce champ peut être affichée comme un ou plusieurs différents champs HTML,
selon la valeur des options ``expanded`` et ``multiple`` :

+-----------------------------------------------+----------+----------+
| Balise HTML                                   | expanded | multiple |
+===============================================+==========+==========+
| Liste déroulante                              | false    | false    |
+-----------------------------------------------+----------+----------+
| Liste déroulante (avec attribut ``multiple``) | false    | true     |
+-----------------------------------------------+----------+----------+
| Boutons radio                                 | true     | false    |
+-----------------------------------------------+----------+----------+
| Checkboxes                                    | true     | true     |
+-----------------------------------------------+----------+----------+ 