trim
~~~~

**type**: ``Boolean`` **default**: ``true``

Si cette option est à true, les espaces d'une chaîne de caractères soumise
dans un formulaire seront supprimés grâce à la fonction ``trim()`` quand
les données seront associées au formulaire. Cela garantit que, si une valeur
est soumise avec des espaces en trop, ils seront supprimés avant que la donnée
ne soit intégrée à l'objet sous-jacent.
