user_timezone
~~~~~~~~~~~~~

**type**: ``string`` **default**: Fuseau horaire par défaut du système

Fuseau horaire qui déterminera comment la donnée doit être affichée à l'utilisateur
(et par conséquent cela concerne aussi les données soumises par l'utilisateur).
Il doit faire partie des `fuseaux horaires supportés par PHP`_

.. _`fuseaux horaires supportés par PHP`: http://php.net/manual/fr/timezones.php