* **Options de Configuration**

  Vous êtes-vous déjà demandé quelles options de configuration étaient disponibles
  dans des fichiers comme ``app/config/config.yml``? Dans cette partie, toute
  la configuration disponible est décomposée en plusieurs parties, une pour chaque
  clé (ex ``framework``), qui définissent chaque section possible de votre
  configuration Symfony2.

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* **Formulaires et Validation**

  * :doc:`Types de champs de formulaires de référence</reference/forms/types>`
  * :doc:`Contraintes de validation de référence </reference/constraints>`
  * :doc:`Fonctions Twig de référence</reference/forms/twig_reference>`

* **Autres sujets**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/requirements`
