Champs de type Texte
~~~~~~~~~~~~~~~~~~~~

* :doc:`text </reference/forms/types/text>`
* :doc:`textarea </reference/forms/types/textarea>`
* :doc:`email </reference/forms/types/email>`
* :doc:`integer </reference/forms/types/integer>`
* :doc:`money </reference/forms/types/money>`
* :doc:`number </reference/forms/types/number>`
* :doc:`password </reference/forms/types/password>`
* :doc:`percent </reference/forms/types/percent>`
* :doc:`search </reference/forms/types/search>`
* :doc:`url </reference/forms/types/url>`

Champs de type Choice
~~~~~~~~~~~~~~~~~~~~~

* :doc:`choice </reference/forms/types/choice>`
* :doc:`entity </reference/forms/types/entity>`
* :doc:`country </reference/forms/types/country>`
* :doc:`language </reference/forms/types/language>`
* :doc:`locale </reference/forms/types/locale>`
* :doc:`timezone </reference/forms/types/timezone>`
* :doc:`currency </reference/forms/types/currency>`

Champs de type Date et Time
~~~~~~~~~~~~~~~~~~~~~~~~~~~

* :doc:`date </reference/forms/types/date>`
* :doc:`datetime </reference/forms/types/datetime>`
* :doc:`time </reference/forms/types/time>`
* :doc:`birthday </reference/forms/types/birthday>`

Autres champs
~~~~~~~~~~~~~

* :doc:`checkbox </reference/forms/types/checkbox>`
* :doc:`file </reference/forms/types/file>`
* :doc:`radio </reference/forms/types/radio>`

Champs de type Groupe
~~~~~~~~~~~~~~~~~~~~~

* :doc:`collection </reference/forms/types/collection>`
* :doc:`repeated </reference/forms/types/repeated>`

Champs cachés
~~~~~~~~~~~~~

* :doc:`hidden </reference/forms/types/hidden>`

Boutons
~~~~~~~

* :doc:`button</reference/forms/types/button>`
* :doc:`reset</reference/forms/types/reset>`
* :doc:`submit</reference/forms/types/submit>`

Champs de base
~~~~~~~~~~~~~~

* :doc:`form </reference/forms/types/form>`