Contraintes de bases
~~~~~~~~~~~~~~~~~~~~

Voici les contraintes de base : utilisez les afin de vérifier des données
basiques à propos de la valeur d'une propriété ou de la valeur retournée
par une méthode de votre objet.

* :doc:`NotBlank </reference/constraints/NotBlank>`
* :doc:`Blank </reference/constraints/Blank>`
* :doc:`NotNull </reference/constraints/NotNull>`
* :doc:`Null </reference/constraints/Null>`
* :doc:`True </reference/constraints/True>`
* :doc:`False </reference/constraints/False>`
* :doc:`Type </reference/constraints/Type>`

Contraintes sur les chaînes de caractères
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* :doc:`Email </reference/constraints/Email>`
* :doc:`Length </reference/constraints/Length>`
* :doc:`Url </reference/constraints/Url>`
* :doc:`Regex </reference/constraints/Regex>`
* :doc:`Ip </reference/constraints/Ip>`

Contraintes sur les nombres
~~~~~~~~~~~~~~~~~~~~~~~~~~~

* :doc:`Range </reference/constraints/Range>`

Contraintes comparatives
~~~~~~~~~~~~~~~~~~~~~~~~

* :doc:`EqualTo </reference/constraints/EqualTo>`
* :doc:`NotEqualTo </reference/constraints/NotEqualTo>`
* :doc:`IdenticalTo </reference/constraints/IdenticalTo>`
* :doc:`NotIdenticalTo </reference/constraints/NotIdenticalTo>`
* :doc:`LessThan </reference/constraints/LessThan>`
* :doc:`LessThanOrEqual </reference/constraints/LessThanOrEqual>`
* :doc:`GreaterThan </reference/constraints/GreaterThan>`
* :doc:`GreaterThanOrEqual </reference/constraints/GreaterThanOrEqual>`

Contraintes sur les dates
~~~~~~~~~~~~~~~~~~~~~~~~~

* :doc:`Date </reference/constraints/Date>`
* :doc:`DateTime </reference/constraints/DateTime>`
* :doc:`Time </reference/constraints/Time>`

Contraintes sur les collections
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* :doc:`Choice </reference/constraints/Choice>`
* :doc:`Collection </reference/constraints/Collection>`
* :doc:`Count </reference/constraints/Count>`
* :doc:`UniqueEntity </reference/constraints/UniqueEntity>`
* :doc:`Language </reference/constraints/Language>`
* :doc:`Locale </reference/constraints/Locale>`
* :doc:`Country </reference/constraints/Country>`

Contraintes sur les fichiers
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* :doc:`File </reference/constraints/File>`
* :doc:`Image </reference/constraints/Image>`

Contraintes sur la finance et autres numéros
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* :doc:`CardScheme </reference/constraints/CardScheme>`
* :doc:`Luhn </reference/constraints/Luhn>`
* :doc:`Iban </reference/constraints/Iban>`
* :doc:`Isbn </reference/constraints/Isbn>`
* :doc:`Issn </reference/constraints/Issn>`

Autres Contraintes
~~~~~~~~~~~~~~~~~~

* :doc:`Callback </reference/constraints/Callback>`
* :doc:`Expression </reference/constraints/Expression>`
* :doc:`All </reference/constraints/All>`
* :doc:`UserPassword </reference/constraints/UserPassword>`
* :doc:`Valid </reference/constraints/Valid>`
