* **Code**

  * :doc:`Bugs </contributing/code/bugs>`
  * :doc:`Patches </contributing/code/patches>`
  * :doc:`Sécurité </contributing/code/security>`
  * :doc:`Tests </contributing/code/tests>`
  * :doc:`Standards syntaxiques</contributing/code/standards>`
  * :doc:`Conventions de codage</contributing/code/conventions>`
  * :doc:`Licence </contributing/code/license>`

* **Documentation**

  * :doc:`Résumé </contributing/documentation/overview>`
  * :doc:`Format </contributing/documentation/format>`
  * :doc:`Traductions </contributing/documentation/translations>`
  * :doc:`License </contributing/documentation/license>`

* **Communauté**

  * :doc:`Processus de sortie de versions </contributing/community/releases>`
  * :doc:`Réunions IRC </contributing/community/irc>`
  * :doc:`Autres ressources </contributing/community/other>`